/**
 * Single source of truth for identity, contact details and links.
 *
 * ── Edit these values and the whole site updates ────────────────────────────
 *  EMAIL       → contact address used by the contact section and footer
 *  GITHUB_URL  → set to '' to hide every GitHub link automatically
 *  RESUME_URL  → the downloadable PDF, generated by `npm run resume`
 *
 *  These are duplicated in resume/resume.html — update both when they change.
 * ---------------------------------------------------------------------------
 */

export const EMAIL = 'jainaditya0404@gmail.com'

export const LINKEDIN_URL = 'https://www.linkedin.com/in/jain04/'

export const GITHUB_URL = 'https://github.com/jain04'

/**
 * Generated from resume/resume.html by `npm run resume`.
 *
 * Built through BASE_URL because Vite rewrites asset paths in index.html but
 * not string literals in JS — a bare '/Aditya-Jain-Resume.pdf' would 404 on the
 * GitHub Pages project path. BASE_URL is '/' in dev and '/portfolio/' in build.
 */
export const RESUME_URL = `${import.meta.env.BASE_URL}Aditya-Jain-Resume.pdf`

export const profile = {
  name: 'Aditya Jain',
  shortName: 'Aditya',
  role: 'Full-Stack Software Engineer',
  company: 'BFirst',
  specialisms: ['SaaS', 'Automation', 'Integrations', 'AI'],
  coreStack: ['React', 'Angular', 'Node.js', 'Python', 'MongoDB', 'Azure'],
  headline: 'I build software that solves real business problems.',
  subhead:
    'Full-Stack Software Engineer specializing in scalable SaaS platforms, workflow automation, integrations and AI-powered applications.',
  about: [
    "I'm Aditya Jain, a Full-Stack Software Engineer focused on building scalable products, SaaS platforms, automation systems and AI-powered applications.",
    'My work spans frontend development, backend engineering, databases, cloud infrastructure, authentication, reporting, integrations and automation.',
    'I enjoy solving problems where software has to connect systems, simplify complex workflows, and operate reliably at scale.',
  ],
  contactHeading: "Let's build something meaningful.",
  contactCopy:
    "I'm open to Software Engineering opportunities where I can work on scalable products, SaaS platforms, automation, AI, integrations and challenging engineering problems.",
} as const

export type SocialLink = {
  label: string
  href: string
  icon: 'linkedin' | 'github' | 'mail' | 'resume'
}

/** Only returns links that are actually configured — never renders a dead link. */
export const socialLinks: SocialLink[] = [
  { label: 'LinkedIn', href: LINKEDIN_URL, icon: 'linkedin' as const },
  { label: 'GitHub', href: GITHUB_URL, icon: 'github' as const },
  { label: 'Email', href: EMAIL ? `mailto:${EMAIL}` : '', icon: 'mail' as const },
  { label: 'Resume', href: RESUME_URL, icon: 'resume' as const },
].filter((link) => link.href.length > 0)
